apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: thiolengkiat413/order-service
    newTag: dev-4

replicas:
  - name: order-service
    count: 1

patches:
  - path: service-nodeport-patch.yaml
    target:
      kind: Service
      name: order-service
  - path: ingress-host-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: order-service
